### ISSUE TITLE
Python-passed workflow failing

### ISSUE THREAD

**Issue by Garulf** [Flow-Launcher/Flow.Launcher.PluginsManifest#95]
The python-passed workflow is failing because it uses GitHub's bot account to commit changes. However it does not have write access to the repo.

@jjw24

**Comment by jjw24** [comment]
use the same secret as the updater.

**Comment by Garulf** [comment]
Done, https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/pull/96

**Comment by jjw24** [comment]
hmm still failed, could you take another look. how come you are using a github bot account to push? that wont have permission

**Comment by Garulf** [comment]
Hmm.. Im testing the same commit action the updater workflow uses... I'll make a PR if it works
